# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          # Cache will be invalidated when pyproject.toml changes
          cache-dependency-path: |
            pyproject.toml

      - name: Bootstrap (create .venv, editable install, import smoke test)
        run: make bootstrap
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'

      - name: Run hello-world ETL
        run: make hello

      - name: Run tests
        run: make test

      - name: Build coverage registry
        run: make coverage
